export const GET_OPERATIONS = "GET_OPERATIONS";
export const GET_BALANCE = "GET_BALANCE";
export const GET_FINAL_INCOME = "GET_FINAL_INCOME";
export const GET_FINAL_EXPENDITURE = "GET_FINAL_EXPENDITURE"
export const POST_OPERATION = "POST_OPERATION";
export const DELETE_OPERATION = "DELETE_OPERATION";
export const PUT_OPERATION = "PUT_OPERATION";
